Updated all launch-scripts to parse auv-specific launch arguments
vortexntnu/uuv-simulator pull request #34
Opened 2021-04-11 10:43 UTC by ingar-eh

Discovered that only cybernetics_sim has the Beluga-model supported, so I made this quick change to enable the other launches to include the Beluga-model as well.

2021-04-11 10:58 UTC, theBadMusician requested changes
- A typo.
- XML formatting.

2021-04-11 10:58 UTC, theBadMusician commented on simulator_launch/launch/combined_launch.launch
> +  <arg name ="sm" defualt ="gladlaks"/>
Typo

2021-04-11 10:58 UTC, theBadMusician commented on simulator_launch/launch/combined_launch.launch
> +<group if="$(eval arg('auv') == 'manta')">
Needs 2 spaces for formatting reasons.

2021-04-11 10:58 UTC, theBadMusician commented on simulator_launch/launch/combined_launch.launch
> +</group>
Add 2 spaces cuz formatting

2021-04-11 10:58 UTC, theBadMusician commented on simulator_launch/launch/combined_launch.launch
> +<group if="$(eval arg('auv') == 'gladlaks')">
Add 2 spaces cuz formatting

2021-04-11 10:58 UTC, theBadMusician commented on simulator_launch/launch/combined_launch.launch
> +</group>
Formatting

2021-04-11 10:58 UTC, theBadMusician commented on simulator_launch/launch/robosub_sim.launch
> +<group if="$(eval arg('auv') == 'manta')">
Formatting

2021-04-11 10:58 UTC, theBadMusician commented on simulator_launch/launch/robosub_sim.launch
> +</group>
Formatting

2021-04-11 10:58 UTC, theBadMusician commented on simulator_launch/launch/vortex_sim.launch
> +<group if="$(eval arg('auv') == 'manta')">
Formatting

2021-04-11 10:58 UTC, theBadMusician commented on simulator_launch/launch/vortex_sim.launch
> +</group>
Formatting

2021-04-19 11:08 UTC, ingar-eh reviewed
Good formatting

2021-04-19 13:23 UTC, theBadMusician commented
Looks good! 👍 🐋 🐋 👍

2021-04-19 13:24 UTC, theBadMusician approved these changes

2021-04-19 21:32 UTC, merged